# Generated by Django 5.1.3 on 2024-12-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_pais_cliente_nacimiento_cliente_país_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='país_origen',
            new_name='pais_origen',
        ),
    ]
